[package]
name = "rust-clacc"
version = "0.3.0"
authors = ["John Driscoll <johnoliverdriscoll@gmail.com>"]
description = "Rust implementanion of a CL universal accumulator"
repository = "https://github.com/johnoliverdriscoll/rust-clacc"
documentation = "https://docs.rs/rust-clacc"
license = "MIT"
keywords = ["crypto", "cryptography", "accumulator", "gmp"]
categories = [
  "algorithms",
  "cryptography",
  "data-structures",
  "embedded"
]
edition = "2018"

[lib]
name = "clacc"
path = "src/clacc.rs"

[[bench]]
name = "bench"
path = "src/bench.rs"
harness = false

[features]
default = ["blake2", "rust-gmp", "velocypack"]

[dependencies]
blake2 = {version = "0.9.0", optional = true}
crossbeam = "0.7.3"
generic-array = "0.14.3"
rand = "0.7.3"
rust-gmp = {version = "0.5.0", optional = true}
serde = {version = "1.0.114", features = ["derive"]}
typenum = "1.12.0"
velocypack = {version = "0.1.1", optional = true}

[dev-dependencies]
criterion = "0.3.3"
num_cpus = "1.13.0"
