[package]
name = "rust-clacc"
version = "2.2.1"
authors = ["John Driscoll <johnoliverdriscoll@gmail.com>"]
description = "Rust implementanion of a CL universal accumulator"
repository = "https://github.com/johnoliverdriscoll/rust-clacc"
documentation = "https://docs.rs/rust-clacc"
license = "MIT"
keywords = ["crypto", "cryptography", "accumulator", "gmp"]
categories = [
  "algorithms",
  "cryptography",
  "data-structures",
  "embedded"
]
edition = "2021"

[lib]
name = "clacc"
path = "src/clacc.rs"

[[bench]]
name = "bench"
path = "src/bench.rs"
harness = false

[features]
default = ["blake2", "gmp"]
blake2 = ["dep:blake2"]
gmp = ["dep:rust-gmp"]
ripemd = ["dep:ripemd"]

[dependencies]
blake2 = {version = "0.10.6", optional = true}
ripemd = {version = "0.1.3", optional = true}
rust-gmp = {version = "0.5.0", optional = true}

[dev-dependencies]
criterion = "0.4.0"
crossbeam = "0.8.2"
num_cpus = "1.15.0"
rand = "0.8.5"
